import { createSlice } from "@reduxjs/toolkit";
// createSlice is a function from the @reduxjs/toolkit library that is used to create a slice of the Redux state.
// A slice is a collection of Redux reducer logic and actions for a single feature of the application. 
// In this case, we are creating a slice for managing the user state in our application.

const userSlice = createSlice({
  name: "user",
  initialState: null,
  reducers: {
    // addUser is a reducer function that takes the current state
    //  and an action as arguments and returns the new state.
    // state is null initially, and when the addUser action is dispatched, it will update the state
    //  to the payload of the action, 
    // which is the user data returned from the backend after a successful login.
    //  The removeUser reducer function will reset the user state back to null
    //  when the user logs out.
    addUser: (_, action) => {
      return action.payload;
    },
    removeUser: () => {
      return null;
    },
  },
});

export const { addUser, removeUser } = userSlice.actions;
// We export the addUser and removeUser action creators so that we 
// can dispatch these actions from our components to update the user
//  state in the Redux store.

export default userSlice.reducer;
// We export the reducer function generated by createSlice
//  as the default export of this file.
